app = 'rails-bot-chat'
primary_region = 'ewr'

[build]

[env]
  RAILS_LOG_TO_STDOUT = "1"
  HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.status]
    port = 8080
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"

[mounts]
  source = "rails_bot_data"
  destination = "/data"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
